### PR TITLE
Yolov8

### PR DESCRIPTION
**Pull request by philipqueen**
This PR adds a working yolo v8 pose tracker. This was MUCH easier than trying to get MMPose working, which I haven't been able to figure out yet. 

I suspect we'll need to make some changes to how the results are stored to account for the multi person tracking. 

Screen Shot 2023-05-15 at 1 06 27 PM

### CODE REVIEW

**Review by jonmatthis — APPROVED** [review]

**Comment by jonmatthis** [comment]
@philipqueen  - I mightbe trying to move faster than normal while I'm at VSS, so I might start pushing some of your PR's through without waiting for you to click the Happy Green Button, if thats alright!

**Comment by philipqueen** [comment]
@jonmatthis That's all good with me!

**Comment by jonmatthis** [comment]
Was also thinking that it would be cool if you made a separate tracker that handled some of the object detection methods in YOLO, or maybe one that implements the segment anything model that @trentwirth was talking about

Just make separate Trackers for each method for now (so we'll have one for YOLO person tracking, another for YOLO objects, and a third for YOLO segment anything) 

You can use the Quine.py method and copy the base tracker with a couple of examples, plop it into The Machine and it should handle things pretty well for you.

Some of The trackers might not have an obvious pixel x pixel y, in that case just take the average of bounding boxes and blobs etc and just use that. 

Try to maintain the general pattern but feel free to be creative within each implementation as needed.

Whee!

**Comment by philipqueen** [comment]
Great that sounds really fun! I'll take a look at it.

**Comment by philipqueen** [comment]
@jonmatthis see #3 for YOLO object detection and #4 for Segment Anything. There's almost certainly errors or weirdness in how the results are being stored, I'm going to look into that next. Getting them both to display feels amazing though!

**Pull request merged**
